# -*- coding: utf-8 -*-
"""IScore.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fQNgwoK7B_sbQff9oQqiNT7qH1C4rIaN
"""

import os
import math
import cv2
import numpy as np
import mediapipe as mp
from ultralytics import YOLO
from deep_sort_realtime.deepsort_tracker import DeepSort

from google.colab import drive
from google.colab.patches import cv2_imshow

# Mount Google Drive
drive.mount('/content/drive/', force_remount=True)

# ---------------- Ball Tracker ----------------
class BallTracker:
    def __init__(self):
        self.kf = cv2.KalmanFilter(4, 2)
        self.kf.measurementMatrix = np.array([[1,0,0,0],[0,1,0,0]], np.float32)
        self.kf.transitionMatrix = np.array([[1,0,1,0],[0,1,0,1],[0,0,1,0],[0,0,0,1]], np.float32)
        self.kf.processNoiseCov = np.eye(4, dtype=np.float32) * 0.08
        self.kf.measurementNoiseCov = np.eye(2, dtype=np.float32) * 0.12
        self.kf.errorCovPost = np.eye(4, dtype=np.float32) * 0.1
        self.kf.statePost = np.zeros((4,1), np.float32)
        self.initialized = False

    def update(self, x, y):
        x, y = float(x), float(y)
        if not self.initialized:
            self.kf.statePost = np.array([[x],[y],[0],[0]], np.float32)
            self.initialized = True
            print(f"[KF INIT] measurement=({x:.1f},{y:.1f})")
        else:
            self.kf.correct(np.array([[x],[y]], np.float32))
            print(f"[KF CORRECT] measurement=({x:.1f},{y:.1f})")
        pred = self.kf.predict()
        px, py = int(pred[0]), int(pred[1])
        print(f"[KF PREDICT] predicted=({px},{py})")
        return px, py

    def predict(self):
        p = self.kf.predict()
        px = int(p[0, 0])
        py = int(p[1, 0])
        return px, py

# ---------------- Collision helpers ----------------
def distance_point_to_rect(px, py, rect):
    x1, y1, x2, y2 = rect
    dx = max(x1 - px, 0, px - x2)
    dy = max(y1 - py, 0, py - y2)
    return math.hypot(dx, dy)

def line_intersects_rect_with_radius(p1, p2, rect, radius=10):
    steps = max(abs(p2[0]-p1[0]), abs(p2[1]-p1[1]))
    if steps == 0:
        steps = 1
    for i in range(steps+1):
        t = i/steps
        x = int(p1[0]*(1-t) + p2[0]*t)
        y = int(p1[1]*(1-t) + p2[1]*t)
        if distance_point_to_rect(x, y, rect) <= radius:
            return True
    return False

# ---------------- Clip Extraction ----------------
def extract_clip(start_sec, clip_num, input_video, fps, width, height, clip_length=1.0):
    cap = cv2.VideoCapture(input_video)
    cap.set(cv2.CAP_PROP_POS_FRAMES, int(start_sec*fps))
    out_name = f'clip_{clip_num}.mp4'
    out = cv2.VideoWriter(out_name, cv2.VideoWriter_fourcc(*'mp4v'), fps, (width,height))
    frames_to_write = int(clip_length*fps)
    for _ in range(frames_to_write):
        ret, frame = cap.read()
        if not ret:
            break
        out.write(frame)
    cap.release()
    out.release()
    return out_name

# ---------------- Ball Detection ----------------
def detect_ball_in_frame(frame, prev_gray, ball_tracker, ball_path, ball_positions,
                        last_ball_pos, frames_since_seen, frame_idx, max_ball_speed=100):
    """Detect ball position using optical flow and update tracking."""
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    flow = cv2.calcOpticalFlowFarneback(prev_gray, gray, None, 0.5, 3, 15, 3, 5, 1.2, 0)
    mag, ang = cv2.cartToPolar(flow[..., 0], flow[..., 1])
    mag = cv2.GaussianBlur(mag, (5, 5), 0)
    motion_mask = (mag > np.percentile(mag, 99.5)).astype(np.uint8)
    contours, _ = cv2.findContours(motion_mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    cx, cy = None, None
    if contours:
        max_val, best_cnt = 0, None
        for cnt in contours:
            if cv2.contourArea(cnt) < 2 or cv2.contourArea(cnt) > 1000:
                continue
            mask = np.zeros_like(mag, np.uint8)
            cv2.drawContours(mask, [cnt], -1, 255, -1)
            mean_val = cv2.mean(mag, mask=mask)[0]
            if mean_val > max_val:
                max_val, best_cnt = mean_val, cnt
        if best_cnt is not None:
            x, y, wbox, hbox = cv2.boundingRect(best_cnt)
            cx, cy = x + wbox // 2, y + hbox // 2

    # Update ball tracking
    if cx is not None and cy is not None:
        ball_pos = ball_tracker.update(cx, cy)
        ball_positions.append((frame_idx, ball_pos[0], ball_pos[1]))
        frames_since_seen = 0
        if not ball_path or math.hypot(ball_pos[0] - ball_path[-1][0], ball_pos[1] - ball_path[-1][1]) < max_ball_speed:
            ball_path.append(ball_pos)
        last_ball_pos = ball_pos
    else:
        frames_since_seen += 1
        if frames_since_seen <= 5 and last_ball_pos is not None:
            pred_pos = ball_tracker.update(last_ball_pos[0], last_ball_pos[1])
            ball_positions.append((frame_idx, pred_pos[0], pred_pos[1]))
            dx = pred_pos[0] - last_ball_pos[0]
            dy = pred_pos[1] - last_ball_pos[1]
            dist = math.hypot(dx, dy)
            if dist <= max_ball_speed and (not ball_path or dist < max_ball_speed):
                ball_path.append(pred_pos)
                last_ball_pos = pred_pos
            else:
                last_ball_pos = None

    return gray, last_ball_pos, frames_since_seen

# ---------------- Player Detection ----------------
def detect_players(frame, model, tracker):
    """Detect and track players using YOLO and DeepSORT."""
    results = model(frame)
    detections = []
    for box, cls, conf in zip(results[0].boxes.xyxy, results[0].boxes.cls, results[0].boxes.conf):
        if int(cls) == 0:
            x1, y1, x2, y2 = map(int, box)
            detections.append(([x1, y1, x2 - x1, y2 - y1], float(conf), "person"))

    tracks = tracker.update_tracks(detections, frame=frame)
    players = {}
    for track in tracks:
        if not track.is_confirmed():
            continue
        tid = track.track_id
        x1, y1, x2, y2 = map(int, track.to_ltrb())
        players[tid] = (x1, y1, x2, y2)
    return players

# ---------------- Backward Trajectory ----------------
def fit_backward_trajectory(ball_positions, max_length=400):
    """Fit a backward trajectory curve from ball positions."""
    try:
        if len(ball_positions) <= 4:
            return None

        N = min(10, len(ball_positions))
        pts = np.array(ball_positions[-N:])
        frames_arr = pts[:, 0]
        xs = pts[:, 1]
        ys = pts[:, 2]

        # Quadratic fit (nearly linear)
        coeffs_x = np.polyfit(frames_arr, xs, 2)
        coeffs_y = np.polyfit(frames_arr, ys, 2)
        coeffs_x[0] *= 0.01
        coeffs_y[0] *= 0.01
        fit_x = np.poly1d(coeffs_x)
        fit_y = np.poly1d(coeffs_y)

        start_frame = int(frames_arr[0])
        back_frames = np.linspace(start_frame - 60, start_frame, 200)
        curve_points = [(int(fit_x(t)), int(fit_y(t))) for t in back_frames]

        # Limit to last ~max_length pixels
        fitted_line = [curve_points[-1]]
        total_dist = 0.0
        for pt in reversed(curve_points[:-1]):
            prev = fitted_line[-1]
            step_dist = math.hypot(pt[0] - prev[0], pt[1] - prev[1])
            total_dist += step_dist
            fitted_line.append(pt)
            if total_dist >= max_length:
                break
        fitted_line = fitted_line[::-1]
        if len(fitted_line) < 2:
            fitted_line = curve_points[-2:]
        return fitted_line
    except Exception as e:
        print("Backward fit error:", e)
        return None

# ---------------- Collision Detection ----------------
def detect_collisions(frame, players, ball_path, fitted_line, frame_idx, collision_radius=10):
    """Detect collisions between ball paths and players."""
    collisions = []
    for tid, bbox in players.items():
        # Forward path collision
        for j in range(1, len(ball_path)):
            if line_intersects_rect_with_radius(ball_path[j-1], ball_path[j], bbox, radius=collision_radius):
                collisions.append((frame_idx, tid))
                cv2.rectangle(frame, (bbox[0], bbox[1]), (bbox[2], bbox[3]), (0, 255, 255), 3)
                cv2.putText(frame, f"Collision P{tid}", (bbox[0], bbox[1] - 25),
                           cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 255, 255), 2)
                break

        # Backward line collision
        if fitted_line is not None:
            for j in range(1, len(fitted_line)):
                if line_intersects_rect_with_radius(fitted_line[j-1], fitted_line[j], bbox, radius=collision_radius):
                    collisions.append((frame_idx, tid))
                    cv2.rectangle(frame, (bbox[0], bbox[1]), (bbox[2], bbox[3]), (255, 200, 0), 3)
                    cv2.putText(frame, f"Collision (throw) P{tid}", (bbox[0], bbox[1] - 40),
                               cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255, 200, 0), 2)
    return collisions

# ---------------- Drawing ----------------
def draw_players_and_paths(frame, players, ball_path, fitted_line):
    """Draw player bounding boxes and ball paths on frame."""
    for tid, (x1, y1, x2, y2) in players.items():
        cv2.rectangle(frame, (x1, y1), (x2, y2), (0, 255, 0), 2)
        cv2.putText(frame, f"P{tid}", (x1, y1 - 10),
                   cv2.FONT_HERSHEY_SIMPLEX, 0.7, (255, 255, 255), 2)

    for j in range(1, len(ball_path)):
        cv2.line(frame, ball_path[j-1], ball_path[j], (0, 0, 255), 2)

    if fitted_line is not None:
        for j in range(1, len(fitted_line)):
            cv2.line(frame, fitted_line[j-1], fitted_line[j], (255, 0, 0), 2)

# ---------------- Process Single Clip ----------------
def process_single_clip(clip_path, fps, width, height, model, frame_output_dir=None,
                       max_ball_speed=100, collision_radius=10):
    """Process a single video clip to detect collisions."""
    cap = cv2.VideoCapture(clip_path)
    clip_num = clip_path.split('_')[1].split('.')[0]
    out_name = f'clip_{clip_num}_collision.mp4'
    out = cv2.VideoWriter(out_name, cv2.VideoWriter_fourcc(*'mp4v'), fps, (width, height))

    ball_tracker = BallTracker()
    tracker = DeepSort(max_age=30, n_init=3, max_cosine_distance=0.4,
                      embedder="mobilenet", embedder_gpu=True)

    ball_path = []
    ball_positions = []
    fitted_line = None
    players_history = {}
    collisions = []
    last_ball_pos = None
    frames_since_seen = 0
    frame_idx = 0

    ret, prev_frame = cap.read()
    if not ret:
        cap.release()
        out.release()
        return out_name, [], []

    prev_gray = cv2.cvtColor(prev_frame, cv2.COLOR_BGR2GRAY)

    while True:
        ret, frame = cap.read()
        if not ret:
            break

        # Detect ball
        prev_gray, last_ball_pos, frames_since_seen = detect_ball_in_frame(
            frame, prev_gray, ball_tracker, ball_path, ball_positions,
            last_ball_pos, frames_since_seen, frame_idx, max_ball_speed
        )

        # Detect players
        players = detect_players(frame, model, tracker)
        players_history[frame_idx] = players.copy()

        # Draw before collision detection
        draw_players_and_paths(frame, players, ball_path, fitted_line)

        # Detect collisions and fit backward trajectory on first collision
        frame_collisions = detect_collisions(frame, players, ball_path, fitted_line,
                                            frame_idx, collision_radius)
        if frame_collisions and fitted_line is None:
            fitted_line = fit_backward_trajectory(ball_positions)

        collisions.extend(frame_collisions)

        # Display and save frame
        if frame_idx % 1 == 0:
            cv2_imshow(cv2.resize(frame, (640, 360)))

            # Save frame to directory if specified
            if frame_output_dir is not None:
                frame_filename = os.path.join(frame_output_dir, f"clip_{clip_num}_frame_{frame_idx:05d}.jpg")
                cv2.imwrite(frame_filename, frame)

        out.write(frame)
        frame_idx += 1

    cap.release()
    out.release()

    # Extract unique players involved in collisions
    player_arr = list(set(pid for _, pid in collisions))
    return out_name, ball_positions, player_arr

# ---------------- Full Pipeline ----------------
def process_clips(timestamps, input_video, clip_length, fps, width, height, frame_output_dir="frames"):
    """Main pipeline to process multiple video clips."""
    os.makedirs(frame_output_dir, exist_ok=True)
    processed_clips = []
    all_ball_positions = {}
    model = YOLO("yolov8n.pt", verbose=False)

    MAX_BALL_SPEED = 100
    COLLISION_RADIUS = 10

    for i, t in enumerate(timestamps, start=1):
        raw_clip = extract_clip(t, i, input_video, fps, width, height, clip_length)
        out_name, ball_positions, player_arr = process_single_clip(
            raw_clip, fps, width, height, model, frame_output_dir, MAX_BALL_SPEED, COLLISION_RADIUS
        )

        all_ball_positions[i] = ball_positions
        processed_clips.append(out_name)

        if player_arr:
            print(f"Collisions in clip {i}: Players {player_arr}")

    return processed_clips, player_arr

# ---------------- Run ----------------
input_video = '/content/drive/My Drive/iScore-JH/Florence Yalls vs Evansville Otters.mp4'
# input_video = '/content/drive/My Drive/iScore-JH/New York Boulders vsDown East Bird Dawgs.mp4'
# input_video = '/content/drive/My Drive/iScore-JH/Sussex County Miners vs Brockton Rox.mp4'

cap = cv2.VideoCapture(input_video)
fps = cap.get(cv2.CAP_PROP_FPS) or 30.0
width  = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH) or 1280)
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT) or 720)
cap.release()

timestamps = [1724]  # Add more seconds as needed
# timestamps = [3533.7]
processed_clips, player_collisions = process_clips(
    timestamps=timestamps,
    input_video=input_video,
    clip_length=1,
    fps=fps,
    width=width,
    height=height,
    frame_output_dir="frames"
)

print("Processed clips:", processed_clips)
print("Forward Collision Player ID:", player_collisions)

def frames_to_video(frame_dir, output_path, fps):
    import cv2
    import os
    from natsort import natsorted

    frames = [f for f in os.listdir(frame_dir) if f.lower().endswith(('.jpg','.png','.jpeg'))]
    frames = natsorted(frames)

    if not frames:
        print("No frames found.")
        return

    first_frame = cv2.imread(os.path.join(frame_dir, frames[0]))
    h, w, _ = first_frame.shape

    out = cv2.VideoWriter(output_path, cv2.VideoWriter_fourcc(*'mp4v'), fps, (w, h))

    for f in frames:
        img = cv2.imread(os.path.join(frame_dir, f))
        out.write(img)

    out.release()
    print("Video written:", output_path)
import os
import cv2
from natsort import natsorted

def save_video_to_input_folder(frame_dir, input_video_path, fps, output_name="combined_output.mp4"):
    """
    Takes all frames in frame_dir and writes a video in the same folder as input_video_path.
    """
    # Determine parent directory
    parent_dir = os.path.dirname(input_video_path)
    output_path = os.path.join(parent_dir, output_name)

    # Collect frames and sort naturally
    frames = [f for f in os.listdir(frame_dir) if f.lower().endswith((".jpg", ".png", ".jpeg"))]
    frames = natsorted(frames)

    if not frames:
        print("❗ No frames found in", frame_dir)
        return None

    # Read first frame to get resolution
    first = cv2.imread(os.path.join(frame_dir, frames[0]))
    h, w, _ = first.shape

    # Create VideoWriter
    fourcc = cv2.VideoWriter_fourcc(*'avc1')  # H.264 - better compatibility
    out = cv2.VideoWriter(output_path, fourcc, fps, (w, h))

    # Write all frames
    for f in frames:
        img = cv2.imread(os.path.join(frame_dir, f))
        out.write(img)

    out.release()
    print("✅ Video saved to:", output_path)
    return output_path

import os

print("Frame dir exists:", os.path.exists("frames"))
print("Files in frames/:")
print(os.listdir("frames")[:20])

import cv2
print(f"Original video FPS: {fps}")

frame_dir = "frames"
save_video_to_input_folder(frame_dir, input_video, fps)

output_path = save_video_to_input_folder("frames", input_video, fps)
cap = cv2.VideoCapture(output_path)
output_fps = cap.get(cv2.CAP_PROP_FPS)
print(f"Output video FPS: {output_fps}")
cap.release()

position_labels = {
    "1": "Pitcher",
    "2": "Catcher",
    "3": "First Baseman",
    "4": "Second Baseman",
    "5": "Third Baseman",
    "6": "Shortstop",
    "7": "Left Fielder",
    "8": "Center Fielder",
    "9": "Right Fielder",
    "10": "Designated Hitter",
    "X": "Umpire"
}


player_labels = {
    "2": "3",
    "6": "1",
    "3": "X",
    "17": "X"
}

thrower = None
catcher = None

non_umpires = [p for p in player_collisions if position_labels[player_labels[p]] != "Umpire"]

if len(non_umpires) >= 2:
    thrower = position_labels[player_labels[non_umpires[0]]]
    catcher = position_labels[player_labels[non_umpires[1]]]

if thrower and catcher:
    print(f"{thrower} threw it to {catcher}.")
else:
    print("Play information incomplete.")

